### ISSUE TITLE
Initial Milestone List

### ISSUE THREAD

**Issue by AleKobs** [AleKobs/easysaas#1]
Initial Milestone
- [ ] Setup a nextJS project
- [ ] Install ShadCN
- [ ] Install Prisma
- [ ] Configure Prisma
- [ ] Setup a basic database and migration
- [ ] Create Login and Register Pages
- [ ] Create Login and Register Form
- [ ] Handle User creation
- [ ] Handle user login with email/password
- [ ] Handle user login with google / apple
- [ ] Handle Gates and page protection
- [ ] Create a simple landing page
